notifications:
  email:
    recipients:
      - travis-ci@bxlab.pl
    on_success: always
    on_failure: always

branches:
  only:
    - master
    - next-release
    - travis-ci

language: bash

sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
      - openssl

after_success:
  - test $TRAVIS_PULL_REQUEST = false && git push

script:
 - bash -c 'shellcheck -s bash -x src/_import_ sslmerge'
